# Generated by Django 3.2.12 on 2022-04-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=1000)),
                ('zipcode', models.IntegerField(default=98208, max_length=1000)),
            ],
        ),
    ]
