# Generated by Django 3.2.12 on 2022-04-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='body',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='area',
            name='zipcode',
            field=models.IntegerField(default=98208),
        ),
    ]
