# Generated by Django 3.2.12 on 2022-04-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
